# CUSTOMISE:

site_name: Tölvera
repo_url: https://github.com/afhverjuekki/tolvera
repo_name: æ/tolvera

# ONLY CUSTOMISE IF NEEDED:

theme:
  name: "material"
  logo: assets/logo/ae.png
  favicon: assets/favicon/favicon.ico
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.instant
    - toc.follow
    - content.code.copy
    - content.code.select

copyright: ©️ Afhverju Ekki
extra:
  generator: false
  social:
    - icon: material/link
      link: http://æ.is
      name: Afhverju Ekki
    - icon: material/email-outline
      link: mailto:ja@æ.is
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/afhverjuekkiis
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/afhverju.ekki.is
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/jdkarmitage
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/jdkarmitage
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ER7tWds9vM
    - icon: fontawesome/brands/github
      link: https://github.com/afhverjuekki
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/afhverjuekki

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

plugins:
  - search  
  - mkdocstrings
  - include-markdown
  - autorefs
  - mkdocs-video
  - awesome-pages
  - gen-files:
      scripts:
      - scripts/gen_ref_pages.py  

watch:
  - src
